cache:
  pipeline: [~/.yarn]

shared:
  image: node:14

jobs:
  main:
    annotations:
      screwdriver.cd/ram: TURBO
      screwdriver.cd/cpu: TURBO
    steps:
      - install-chrome: ./build-scripts/setup-chrome.sh
      - yarn-cache: yarn config set cache-folder ~/.yarn
      - install: yarn install --frozen-lockfile
      - test: yarn test
      - docs: |
          yarn build-storybook
          sd-step exec core/zip "zip -r $SD_ARTIFACTS_DIR/storybook.zip storybook-static"
    requires:
      - ~pr
      - ~commit
    environment:
      JOBS: 4

  publish:
    requires: main
    steps:
      - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git /tmp/ci
      - publish: |
          . /tmp/ci/git-ssh.sh
          npx semantic-release
    secrets:
      - NPM_TOKEN
      - GH_TOKEN
      - GIT_KEY_BASE64

  docs:
    requires: publish
    steps:
      - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git /tmp/ci
      - yarn-cache: yarn config set cache-folder ~/.yarn
      - install: yarn install --frozen-lockfile
      - docs: |
          . /tmp/ci/git-ssh.sh
          git remote set-url origin `git remote get-url --push origin`
          yarn deploy-storybook
    secrets:
      - GIT_KEY_BASE64
    environment:
      JOBS: 4
