cache:
  pipeline: [~/.npm]

shared:
  image: node:12

jobs:
  main:
    annotations:
      screwdriver.cd/ram: TURBO
      screwdriver.cd/cpu: TURBO
    steps:
      - install-chrome: ./build-scripts/setup-chrome.sh
      - install: npm ci
      - test: npm test
    requires:
      - ~pr
      - ~commit

  publish:
    requires: main
    steps:
      - publish: npx semantic-release --dry-run
    secrets:
      - NPM_TOKEN
      - GH_TOKEN
